---
version: 2
jobs:
  lint: &lint
    docker:
      - image: node:latest
    # environment:
    #   - TEST_SERIES: 1
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v5-{{checksum ".circleci/config.yml"}}
            - v5
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps lint
      - persist_to_workspace: {root: node_modules,  paths: ["*"]}
  node-latest-plugins-generate:
    <<: *lint
    steps: &plugins_generate_steps
      - checkout
      - restore_cache: *restore_cache
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: yarn exec nps test.plugins-generate
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-8-plugins-generate:
    <<: *lint
    docker:
      - image: node:8
    steps: *plugins_generate_steps

  cache:
    <<: *lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - run: yarn add -D mocha-junit-reporter@1
      - run: yarn exec nps test.command
      - save_cache:
          key: v5-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  release:
    <<: *lint
    steps:
      - add_ssh_keys
      - checkout
      - attach_workspace: {at: node_modules}
      - run: .circleci/setup_git
      - run: .circleci/release

workflows:
  version: 2
  oclif:
    jobs:
      - lint
      - node-latest-plugins-generate: {requires: [lint] }

  nightly:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint
      - node-latest-plugins-generate: {requires: [lint] }
      - node-8-plugins-generate: {requires: [lint] }
